<?php

/**
 * @file
 * Logger module file.
 */

/**
 * Implements hook_search_api_db_query_alter().
 */

/**
 * Implements hook_search_api_backend_info_alter().
 *
 * Defines custom backend enhancements for supported search api backends.
 */
function search_api_logger_search_api_backend_info_alter(array &$backend_info) {
  // Solr backend.
  if (isset($backend_info['search_api_solr'])) {
    $backend_info['search_api_solr']['class'] = '\Drupal\search_api_logger\Plugin\search_api\backend\SearchApiLoggerSolrBackend';
  }

  // DB backend.
  if (isset($backend_info['search_api_db'])) {
    $backend_info['search_api_db']['class'] = '\Drupal\search_api_logger\Plugin\search_api\backend\SearchApiLoggerDbBackend';
  }

  // Elastic Search backend.
  // See https://www.drupal.org/node/2906735
  if (isset($backend_info['elasticsearch'])) {
    $backend_info['elasticsearch']['class'] = '\Drupal\search_api_logger\Plugin\search_api\backend\SearchApiLoggerElasticSearchBackend';
  }
}
